### ISSUE TITLE
How can we add the date in the simplest way?

### ISSUE THREAD

**Issue by emrecan-balgun** [nunovieira220/tournament-generator#3]
First of all, thank you for this repo. Health to your labor. My question will be a little simple, but, how can we add the date in the simplest way.

**Comment by nuno-vieira-deel** [comment]
Hey there and thanks!

Is your question about how to add a given date to a game? If yes, you just need to execute a `map` and add it to each game object.

If you want to generate dates, it will depend a lot on the rules you define for each round. For example in football, each game in each round has a different date and time. Other example is just a contest where each round can be on a specific day and the time does not matter or even the entire contest is in that day. It really depends on the tournament type. There are too many possibilities tbh.
