### ISSUE TITLE
Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported

### ISSUE THREAD

**Issue by marquinmpfs** [nunovieira220/tournament-generator#5]
Using the lib I am getting the error: 

`Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported `

if necessary:

import 'react-native-get-random-values';
import { v4 as uuidv4 } from 'uuid';

**Comment by nuno-vieira-deel** [comment]
Created a `v1.4.1` version that removes the uuid dependency to avoid problems with dependencies.

I'm closing this issue since it should be solved.
